// Regenerate the federation-v0 vectors from the reference implementation.
//
//   node spec/federation-v0/vectors/generate.mjs
//
// The committed JSON files are generated by this script and consumed by BOTH
// implementations (test/unit/federation-vectors.test.js here; MyceliumKit's
// Swift mirror in the companion repo). One canonical set, never two — a case
// the Swift side needs is added HERE and regenerated, not forked.
//
// Everything is deterministic: fixed seeds (sha256 of fixed labels), fixed
// clocks. Ed25519 signing is deterministic (RFC 8032), so the same seeds and
// clocks always yield the same signatures — in any language.

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { keyFromSeed, publicKeyHex, idForKey } from '../../../server/plugins/federation/keys.js';
import {
  rowId, makeRow, makeNetworkPassport, makeAgentPassport, makeGrant,
  makeVisitRecord, makeBundle, adjudicateImport, episodeRow
} from '../../../server/plugins/federation/protocol.js';

var HERE = path.dirname(fileURLToPath(import.meta.url));

function seedFor(label) {
  return crypto.createHash('sha256').update(label, 'utf8').digest('hex');
}

// ---- fixed test material ---------------------------------------------------

var HOST_SEED = seedFor('mycelium-federation-v0/test/host');
var GUEST_SEED = seedFor('mycelium-federation-v0/test/guest-network');
var AGENT_SEED = seedFor('mycelium-federation-v0/test/agent-a');

var host = keyFromSeed(HOST_SEED);
var guest = keyFromSeed(GUEST_SEED);
var agentA = keyFromSeed(AGENT_SEED);

var HOST_ID = idForKey(host);       // network 2 — the lab server
var GUEST_ID = idForKey(guest);     // network 1 — the phone
var AGENT_ID = idForKey(agentA);

var keys = {
  host_network: { label: 'mycelium-federation-v0/test/host', seed_hex: HOST_SEED, public_key_hex: publicKeyHex(host), network_id: HOST_ID },
  guest_network: { label: 'mycelium-federation-v0/test/guest-network', seed_hex: GUEST_SEED, public_key_hex: publicKeyHex(guest), network_id: GUEST_ID },
  agent_a: { label: 'mycelium-federation-v0/test/agent-a', seed_hex: AGENT_SEED, public_key_hex: publicKeyHex(agentA), agent_id: AGENT_ID }
};

var T0 = '2026-09-24T10:00:00Z'; // passports/grant issued, visit starts
var T1 = '2026-09-24T10:05:00Z'; // the row is learned
var T3 = '2026-09-24T11:00:00Z'; // visit ends, souvenir issued
var T_EXPIRES = '2026-09-24T12:00:00Z';
var NOW_VALID = Date.parse('2026-09-24T10:30:00Z');
var NOW_EXPIRED = Date.parse('2026-09-24T12:30:00Z');
var VISIT_ID = 'v3f0c1a2b3c4d5e6f708192a3b4c5d6e';

var hostPassport = makeNetworkPassport(host, HOST_ID, {
  name: 'gilbert-lab',
  policy: { visitors: true, kinds_writable: ['aboutYou'], kinds_exportable: ['aboutYou'] },
  issued_at: T0
});

var agentPassport = makeAgentPassport(guest, {
  agent_id: AGENT_ID,
  name: 'Qurio',
  species: 'qurio',
  home_network: GUEST_ID,
  capabilities: ['dance', 'memory'],
  consent: { share_dances: true, share_memories: true },
  issued_at: T0
});

var grant = makeGrant(host, {
  visit_id: VISIT_ID,
  host_network: HOST_ID,
  agent_id: AGENT_ID,
  home_network: GUEST_ID,
  kinds_writable: ['aboutYou'],
  kinds_readable: [],
  kinds_exportable: ['aboutYou'],
  issued_at: T0,
  expires_at: T_EXPIRES
});

var danceContent = {
  kind: 'aboutYou',
  key: 'dance.pickles-foxtrot',
  text: "Learned the Pickles Foxtrot at a friend's house — 8 counts, ends on the left foot.",
  source: 'visit',
  at: T1,
  supersedes: null
};

// Every escaping rule cjson exercises (see also spec README §1): `\"`, `\\`,
// the \b-free shorthands JSON.stringify emits (\t \n \r), control chars with
// no shorthand as lowercase \u00xx, and non-ASCII left literal.
var escapeText = 'He said "yo"\t— back\\slash\nand a line\r\u0001ctl-1\u001fctl-31 café 🍄';

var danceRow = makeRow(agentA, AGENT_ID, danceContent, {
  agent: AGENT_ID, network: HOST_ID, home: GUEST_ID, visit: VISIT_ID
});

var visitRecord = makeVisitRecord({
  visit_id: VISIT_ID,
  host_network: HOST_ID,
  agent_id: AGENT_ID,
  home_network: GUEST_ID,
  grant_id: grant.grant_id,
  started_at: T0,
  ended_at: T3
});

var bundle = makeBundle(host, {
  host_passport: hostPassport,
  agent_passport: agentPassport,
  visit: visitRecord,
  rows: [danceRow],
  issued_at: T3
});

// A tampered row: same content shape, text mutated, id recomputed so the
// tamper is in the SIGNATURE (the content-id check passes, the sig fails).
var tamperedRow = Object.assign({}, danceRow, {
  text: 'Learned the Pickles Foxtrot — 8 counts, ends on the right foot.',
  id: rowId(Object.assign({}, danceContent, { text: 'Learned the Pickles Foxtrot — 8 counts, ends on the right foot.' }))
});

// A tampered bundle: one hex digit of the host signature flipped.
var tamperedBundleSig = ('0' === bundle.sig_by_host[0] ? '1' : '0') + bundle.sig_by_host.slice(1);
var tamperedBundle = Object.assign({}, bundle, { sig_by_host: tamperedBundleSig });

// A pre-existing HOME row with the same (kind, key) as the dance — the
// supersede-candidate collision.
var HOME_ROW_ID = rowId({
  kind: 'aboutYou', key: 'dance.pickles-foxtrot',
  text: 'Knows a little dance — picked it up somewhere.',
  source: 'chat', at: '2026-09-20T09:00:00Z', supersedes: null
});

function write(name, obj) {
  fs.writeFileSync(path.join(HERE, name), JSON.stringify(obj, null, 2) + '\n');
  console.log('wrote', name);
}

// ---- 01 canonical row ------------------------------------------------------

write('01-canonical-row.json', {
  name: 'canonical-row',
  description: 'The canonical JSON form of a row\'s content fields and its content-addressed id (sha256 of that form). key/supersedes are null when unset, never omitted.',
  keys: keys,
  cases: [
    {
      name: 'dance-no-supersedes',
      content: { kind: 'aboutYou', key: 'dance.pickles-foxtrot', text: danceContent.text, source: 'visit', at: T1, supersedes: null },
      expected: { cjson: JSON.stringify({ at: T1, key: 'dance.pickles-foxtrot', kind: 'aboutYou', source: 'visit', supersedes: null, text: danceContent.text }), id: rowId(danceContent) }
    },
    {
      name: 'with-supersedes',
      content: { kind: 'aboutMe', key: null, text: 'My favorite game is skee-ball.', source: 'game', at: T1, supersedes: 'ab'.repeat(32) },
      expected: { cjson: JSON.stringify({ at: T1, key: null, kind: 'aboutMe', source: 'game', supersedes: 'ab'.repeat(32), text: 'My favorite game is skee-ball.' }), id: rowId({ kind: 'aboutMe', key: null, text: 'My favorite game is skee-ball.', source: 'game', at: T1, supersedes: 'ab'.repeat(32) }) }
    },
    {
      // The escaping alphabet a second implementation must not guess
      // (review A nit 11): quotes, backslash, the JSON control-character
      // shorthands, two raw control chars with no shorthand, and non-ASCII
      // left literal (UTF-8, never \u-escaped). The pinned cjson string is
      // the byte-level contract.
      name: 'escaping-alphabet',
      content: { kind: 'aboutYou', key: 'escape.zoo', text: escapeText, source: 'visit', at: T1, supersedes: null },
      expected: { cjson: JSON.stringify({ at: T1, key: 'escape.zoo', kind: 'aboutYou', source: 'visit', supersedes: null, text: escapeText }), id: rowId({ kind: 'aboutYou', key: 'escape.zoo', text: escapeText, source: 'visit', at: T1, supersedes: null }) }
    }
  ]
});

// ---- 02 passport -------------------------------------------------------------

write('02-passport.json', {
  name: 'agent-passport',
  description: 'The agent passport and its sig_by_home — the home network\'s Ed25519 signature over cjson(passport minus sig_by_home).',
  keys: keys,
  input: {
    fields: { agent_id: AGENT_ID, name: 'Qurio', species: 'qurio', home_network: GUEST_ID, capabilities: ['dance', 'memory'], consent: { share_dances: true, share_memories: true }, issued_at: T0 },
    signed_by: 'guest_network'
  },
  expected: { passport: agentPassport }
});

// ---- 03 grant ------------------------------------------------------------------

write('03-grant.json', {
  name: 'grant',
  description: 'The visitor grant signed by the host network, and its validity window: issued_at <= now < expires_at.',
  keys: keys,
  input: {
    fields: { visit_id: VISIT_ID, host_network: HOST_ID, agent_id: AGENT_ID, home_network: GUEST_ID, kinds_writable: ['aboutYou'], kinds_readable: [], kinds_exportable: ['aboutYou'], issued_at: T0, expires_at: T_EXPIRES },
    signed_by: 'host_network'
  },
  expected: {
    grant: grant,
    verify: [
      { now_ms: NOW_VALID, result: { valid: true, grant_id: grant.grant_id, visit_id: VISIT_ID } },
      { now_ms: NOW_EXPIRED, result: { valid: false, reason: 'grant-expired' } }
    ]
  }
});

// ---- 04 souvenir bundle ----------------------------------------------------

write('04-souvenir-bundle.json', {
  name: 'souvenir-bundle',
  description: 'The souvenir the host signs on leave: both passports (self-contained verification), the visit record, and only the rows the grant\'s export policy allows — each row still carrying the agent\'s own signature.',
  keys: keys,
  input: {
    host_passport_fields: { name: 'gilbert-lab', policy: { visitors: true, kinds_writable: ['aboutYou'], kinds_exportable: ['aboutYou'] }, issued_at: T0 },
    agent_passport_fields: { agent_id: AGENT_ID, name: 'Qurio', species: 'qurio', home_network: GUEST_ID, capabilities: ['dance', 'memory'], consent: { share_dances: true, share_memories: true }, issued_at: T0 },
    row: danceContent,
    visit_fields: { visit_id: VISIT_ID, host_network: HOST_ID, agent_id: AGENT_ID, home_network: GUEST_ID, grant_id: grant.grant_id, started_at: T0, ended_at: T3 },
    issued_at: T3,
    signed_by: 'host_network'
  },
  expected: { bundle: bundle }
});

// ---- 05 import outcomes ------------------------------------------------------

write('05-import-outcomes.json', {
  name: 'import-outcomes',
  description: 'Border verification and import adjudication: fresh import, replay (content-addressed dedupe), supersede candidate (never a silent supersede), tampered signature, expired grant.',
  keys: keys,
  cases: [
    {
      name: 'verify-row-tampered',
      input: { row: tamperedRow },
      expected: { valid: false, reason: 'row-sig' }
    },
    {
      name: 'verify-bundle-tampered',
      input: { bundle: tamperedBundle },
      expected: { valid: false, reason: 'bundle-sig' }
    },
    {
      name: 'import-fresh',
      input: { bundle: bundle, home_rows: [] },
      expected: { outcomes: [{ row_id: danceRow.id, outcome: 'imported' }], episode: episodeRow(bundle) }
    },
    {
      name: 'import-replay',
      input: { bundle: bundle, home_rows: [{ id: danceRow.id, kind: 'aboutYou', key: 'dance.pickles-foxtrot', superseded_by: null, candidate: false }] },
      expected: { outcomes: [{ row_id: danceRow.id, outcome: 'replayed' }], episode: episodeRow(bundle) }
    },
    {
      name: 'import-supersede-candidate',
      input: { bundle: bundle, home_rows: [{ id: HOME_ROW_ID, kind: 'aboutYou', key: 'dance.pickles-foxtrot', superseded_by: null, candidate: false }] },
      expected: adjudicateImport(bundle, [{ id: HOME_ROW_ID, kind: 'aboutYou', key: 'dance.pickles-foxtrot', superseded_by: null, candidate: false }])
    }
  ]
});

console.log('done.');
