#!/bin/bash
# Mycelium — Local-First Setup
#
# Generates secrets and creates .env for a self-hosted Mycelium instance.
# No cloud dependency — everything runs on your machine.
#
# Usage:
#   bash scripts/local-setup.sh
#   docker compose up -d

set -e

echo ""
echo "  ┌─────────────────────────────────┐"
echo "  │     Mycelium Local Setup         │"
echo "  │     Self-hosted, no cloud        │"
echo "  └─────────────────────────────────┘"
echo ""

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo "Error: Node.js is required. Install from https://nodejs.org/"
    exit 1
fi

# Generate secrets
JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
ADMIN_KEY=$(node -e "console.log('dvk_' + require('crypto').randomBytes(24).toString('hex'))")

# Check if .env already exists
if [ -f .env ]; then
    echo "Warning: .env already exists."
    read -p "Overwrite? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

# Write .env
cat > .env << EOF
# Mycelium Local Instance
# Generated by local-setup.sh on $(date)

JWT_SECRET=$JWT_SECRET
ADMIN_KEY=$ADMIN_KEY
PORT=3002

# Uncomment to enable persistent data volume
# DATA_DIR=/data
EOF

echo "Generated .env with:"
echo "  JWT_SECRET: ${JWT_SECRET:0:8}..."
echo "  ADMIN_KEY:  ${ADMIN_KEY:0:12}..."
echo ""

# Check for Docker
if command -v docker &> /dev/null; then
    echo "Docker detected. You can now run:"
    echo ""
    echo "  docker compose up -d"
    echo ""
    echo "Or run without Docker:"
    echo ""
    echo "  npm install && node server/index.js"
    echo ""
else
    echo "Docker not detected. Run directly:"
    echo ""
    echo "  npm install && node server/index.js"
    echo ""
fi

echo "Then open: http://localhost:3002/studio/"
echo ""
echo "First time? Create an admin account in the dashboard."
echo "Then register agents with: npx @mycelium/sdk init"
echo ""
