import { describe, test, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = join(__dirname, '..', '..')

// A stranger who clones this repo sees a flat list of top-level directories.
// Every one of them has to be discoverable: either README.md names it (so a
// reader of README alone can account for every directory), or the directory
// ships its own README.md that explains it. A new top-level directory with
// neither is a mystery to a cold reader — and this gate turns that into a
// red test instead of a silent addition.
//
// The directory set is DERIVED from the repo's TRACKED paths (`git ls-files`,
// never hardcoded, never read off the working tree), and the README text is
// read live. Same commit ⇒ same tracked set ⇒ same rows everywhere: local
// and CI grade the repository, not the operator's disk.
//
// WHY TRACKED-DERIVED (do not "restore" a readdirSync derivation here). The
// previous version walked the live top level with readdirSync, which graded
// whatever happened to sit on the run machine's disk. Both failure modes
// reproduced on master 69b05a6, 2026-09-05:
//   - FALSE RED: an untracked scratch dir (`mkdir zz-scratch` at the root)
//     turned this file red — "top-level directory zz-scratch/ is documented",
//     1 failed | 13 passed (14) — on a commit whose CI run was green. A
//     contributor's local scratch or editor artifact turned their suite red
//     for a reason unrelated to their change — the local-RED ≠ CI-green
//     direction of the gap test/README promises never to open.
//   - COUNT INFLATION: untracked dirs silently added PASSING rows — a
//     residue-carrying dev checkout ran 15 cases in this file where a pristine
//     clone of the same commit ran 13 (release-readiness/ passes via its own
//     README, studio-react/ via the retirement note at README ~:184). "Green"
//     on a dev box was certifying two directories no stranger's clone has.
//
// THE TRADE, so the readdirSync version is not restored as if it were lost
// coverage: an UNTRACKED top-level dir no longer reds this gate. That is
// intended — untracked local state is not repo surface, and the README
// contract has nothing to say about it. The gate's teeth are unchanged where
// they matter: a TRACKED-but-undocumented top-level dir still reds (see the
// bite receipt in the lane notes: `git add` a new top-level dir without a
// README mention or its own README and this file fails; unstage and it
// passes again).
//
// COEXISTENCE with the coverage-command self-red lane (148, branch
// test/m5max/coverage-command-self-red), in both orders: if 148 lands first
// and adds 'coverage' to SKIP_DIRS below, that entry is vestigial-but-
// harmless here — coverage/ is untracked, so it drops out of the tracked set
// on its own. If this lands first, 148's executor gets their cross-check
// invariant (pristine clone and dev checkout reporting the same case count)
// for free in this file.

// node_modules can never appear in `git ls-files` (gitignored), so this
// entry is belt-and-suspenders rather than load-bearing: it stays so a
// force-added (`git add -f node_modules/...`) tooling dir still cannot
// masquerade as undocumented product surface. Dotdirs (.git, .github,
// .claude, ...) are excluded by the leading-dot filter below.
//
// `coverage` is the v8 reporter's output dir, generated by the advertised
// `npm run test:coverage` itself — untracked, so it already drops out of
// the tracked set on its own; the entry stays vestigial-but-harmless (the
// coexistence story the header above describes for lane 148).
const SKIP_DIRS = new Set(['node_modules', 'coverage'])

// Vacuous-green floor: the number of tracked non-dot top-level dirs when this
// derivation landed (2026-09-05, master 69b05a6). A FLOOR, not an equality —
// adding a top-level dir never requires touching it; only deliberately
// removing top-level dirs does. Its job is to make a silently shrunken
// derivation (wrong cwd, partial git output) red instead of letting rows
// vanish and the file report green while grading almost nothing.
const MIN_TRACKED_TOP_LEVEL_DIRS = 12

function trackedTopLevelDirs() {
  let out
  try {
    out = execFileSync('git', ['ls-files', '-z'], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
      // ~1k tracked files today; generous headroom. An overrun throws
      // (ERR_CHILD_PROCESS_STDIO_MAXBUFFER) rather than truncating.
      maxBuffer: 64 * 1024 * 1024,
    })
  } catch (err) {
    // Outside a git checkout (zipball download, sandbox without git) the gate
    // cannot be graded at all. Fail loud with the cause — do NOT fall back to
    // readdirSync (that fallback is the bug this derivation fixes) and do not
    // pass vacuously.
    throw new Error(
      'readme-top-level-dirs gate: `git ls-files` failed in ' + REPO_ROOT +
      ' (' + String(err.message).split('\n')[0] + '). This gate derives its ' +
      'cases from TRACKED paths, so it can only grade a git checkout — a ' +
      'zipball download or a sandbox without git cannot be graded here. Do ' +
      'not reintroduce a readdirSync fallback: reading the working tree is ' +
      'the false-red / count-inflation bug this derivation exists to fix.',
      { cause: err }
    )
  }
  const dirs = new Set()
  for (const entry of out.split('\0')) {
    if (!entry) continue
    const slash = entry.indexOf('/')
    if (slash === -1) continue // top-level FILE (README.md, package.json, ...) — the gate grades directories
    dirs.add(entry.slice(0, slash))
  }
  return [...dirs]
    .filter((name) => !name.startsWith('.')) // dotdirs are tooling/config
    .filter((name) => !SKIP_DIRS.has(name))
    .sort()
}

const readme = readFileSync(join(REPO_ROOT, 'README.md'), 'utf8')
const dirs = trackedTopLevelDirs()

// Vacuous-green guard, before any case is generated: a derivation returning
// nothing would otherwise delete every row below and the file would report
// green while grading nothing. If this fires, the checkout really has no
// tracked paths — say so instead of passing silently.
if (dirs.length === 0) {
  throw new Error(
    'readme-top-level-dirs gate: `git ls-files` produced ZERO tracked paths ' +
    'in ' + REPO_ROOT + ' — refusing to generate an empty case set (every row ' +
    'would vanish and the file would look green). A check that cannot fail ' +
    'is not a check.'
  )
}

describe('every top-level directory is accounted for in README or its own README', () => {
  // Sanity floor: the tracked derivation must yield a real set — non-empty,
  // and at least what this repo tracked when the gate went tracked-derived —
  // before the per-directory loop generates cases. A shrunken set would
  // otherwise make rows disappear and look quietly green.
  test('derived tracked top-level directory set is non-empty and at or above the floor', () => {
    expect(dirs.length).toBeGreaterThan(0)
    expect(dirs.length).toBeGreaterThanOrEqual(MIN_TRACKED_TOP_LEVEL_DIRS)
  })

  for (const dir of dirs) {
    test(`top-level directory "${dir}/" is documented`, () => {
      // A directory is "accounted for" if README.md points at it as a path
      // (the `dir/` form the Architecture tree and Packages table already
      // use), or it carries its own README.md explaining it. We match the
      // path form `dir/` rather than the bare name: common directory names
      // like `tools` and `scripts` appear in README as ordinary English
      // words ("MCP tools", "local models, scripts") without documenting
      // the directory, and a bare-substring match would pass those through
      // as false greens — the exact mystery this gate exists to catch.
      const mentionedInReadme = readme.includes(dir + '/')
      const hasOwnReadme = existsSync(join(REPO_ROOT, dir, 'README.md'))
      expect(mentionedInReadme || hasOwnReadme).toBe(true)
    })
  }
})
